# Generated by Django 3.2.8 on 2021-11-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_visits', '0002_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_visits.purpose'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(choices=[('appointment', 'appointment'), ('treatment', 'treatment')], max_length=100),
        ),
    ]
